services:
  postgres:
    container_name: postgres-lisa
    build: .
    image: postgres-lisa-img  # name of the image we build from dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    volumes:
      - pgdata:/var/lib/postgresql/data # pgdata volume maps to /var inside container
    ports:
      - "5433:5432" # maps hostport to containerport - keeping host 5432 clean since we have a postgres server on host as well
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always

volumes:
  pgdata: